# Generated by Django 5.2.3 on 2025-08-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='image_field/def.jpg', null=True, upload_to='image_field'),
        ),
    ]
